language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - nvm 4.x
  - npm install
  - bower install
  - gem install coveralls-lcov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir instance
  - echo "SECRET_KEY = 'key-for-jenkins';ASSETS_AUTO_BUILD = True" > instance/config.py

script:
  - lettuce --with-xunit pubs_ui/lettuce_testing
  - nosetests pubs_ui --with-coverage --cover-package=pubs_ui
  - karma start tests/js/karma.conf.js

after_success:
  find coverage/ -mindepth 2 -iname '*.info' -exec cp -t coverage/ '{}' +;
  coveralls-lcov -v -n coverage/lcov.info > coverage.json;
  coveralls --merge=coverage/coverage.json
