language: python

python:
  - "2.7"

before_install:
  - sudo apt-get install lcov
  - nvm install 6.10.2

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install
  - node_modules/bower/bin/bower install
  - gem install coveralls-lcov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir instance
  - echo "SECRET_KEY = 'key-for-jenkins';ASSETS_AUTO_BUILD = True" > instance/config.py

script:
  - lettuce --with-xunit pubs_ui/lettuce_testing
  - nosetests  --with-coverage --cover-package=pubs_ui
  - karma start tests/js/manager/karma.conf.js
  - karma start tests/js/metrics/karma.conf.js
  - karma start tests/js/pubswh/karma.conf.js

after_success:
  cp coverage/manager/Firefox*/lcov.info coverage/manager.info;
  cp coverage/metrics/Firefox*/lcov.info coverage/metrics.info;
  cp coverage/pubswh/Firefox*/lcov.info coverage/pubswh.info;
  lcov --add-tracefile coverage/manager.info --add-tracefile coverage/metrics.info --add-tracefile coverage/pubswh.info --output-file coverage/combined.info;
  coveralls-lcov -v -n coverage/combined.info > coverage/combined.json;
  coveralls --merge=coverage/combined.json;
