language: python

python:
  - "2.7"

addons:
  firefox: "latest"

before_install:
  - sudo apt-get install lcov
  - nvm install $(python -c "import json; print(json.loads(open('./assets/package.json').read())['engines']['node'])")

install:
  - make env
  - gem install coveralls-lcov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir coverage

script:
  - make test

after_success:
  cp assets/coverage/manager/Firefox*/lcov.info coverage/manager.info;
  cp assets/coverage/metrics/Firefox*/lcov.info coverage/metrics.info;
  cp assets/coverage/pubswh/Firefox*/lcov.info coverage/pubswh.info;
  lcov --add-tracefile coverage/manager.info --add-tracefile coverage/metrics.info --add-tracefile coverage/pubswh.info --output-file coverage/combined.info;
  coveralls-lcov -v -n ./server/coverage/lcov.info > ./server/coverage/coverage.json
  cd server && env/bin/coveralls --merge=../coverage/combined.json
